# Generated by Django 4.2 on 2024-07-02 14:50

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpost',
            name='embedding',
            field=models.FileField(null=True, upload_to=post.models.embedding_directory),
        ),
        migrations.AddField(
            model_name='lostpost',
            name='embedding',
            field=models.FileField(null=True, upload_to=post.models.embedding_directory),
        ),
    ]
