# Generated by Django 4.2 on 2024-07-10 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_foundpost_embedding_lostpost_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lostpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.lostpost')),
                ('matched', models.ManyToManyField(blank=True, related_name='match', to='post.foundpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
