# Generated by Django 4.2 on 2024-07-23 14:04

import authy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='picture',
            field=models.ImageField(null=True, upload_to=authy.models.cat_avatar_directory),
        ),
    ]
